package com.graphdbplugin.datasource

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertNotEquals
import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.DisplayName
import org.junit.jupiter.api.Test
import java.util.UUID

/**
 * Unit tests for [BoltDataSource].
 *
 * These tests verify the data class semantics, factory method behaviour, UUID
 * generation, and default field values of [BoltDataSource]. No IntelliJ Platform
 * infrastructure is required — all tests are plain JVM / JUnit 5 tests.
 *
 * Coverage targets:
 * - [BoltDataSource.create] factory method
 * - Default field values
 * - UUID generation (non-empty, valid format, uniqueness)
 * - `data class` copy semantics
 * - URL scheme validation helpers (documented conventions)
 */
@DisplayName("BoltDataSource — unit tests")
class BoltDataSourceTest {

    // =========================================================================
    // Factory method tests
    // =========================================================================

    /**
     * Verifies that [BoltDataSource.create] sets the [BoltDataSource.name] and
     * [BoltDataSource.url] fields to the supplied arguments.
     */
    @Test
    @DisplayName("create() — sets name and url from arguments")
    fun testCreateFactory() {
        val name = "My Test Connection"
        val url = "bolt://localhost:7687"

        val ds = BoltDataSource.create(name, url)

        assertEquals(name, ds.name, "name should match the factory argument")
        assertEquals(url, ds.url, "url should match the factory argument")
    }

    /**
     * Verifies that [BoltDataSource.create] applies sensible default values to all
     * fields not specified in the factory call.
     */
    @Test
    @DisplayName("create() — default field values are applied correctly")
    fun testDefaultValues() {
        val ds = BoltDataSource.create("Defaults Test", "bolt://localhost:7687")

        assertEquals("neo4j", ds.username, "default username should be 'neo4j'")
        assertEquals("neo4j", ds.database, "default database should be 'neo4j'")
        assertEquals(false, ds.sslEnabled, "SSL should be disabled by default")
        assertEquals(30, ds.connectionTimeoutSeconds, "default timeout should be 30 seconds")
        assertEquals("#4A90D9", ds.color, "default color should be '#4A90D9'")
    }

    // =========================================================================
    // UUID / ID tests
    // =========================================================================

    /**
     * Verifies that the [BoltDataSource.id] field generated by [BoltDataSource.create]
     * is non-null, non-blank, and conforms to the standard UUID format
     * (`xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx`).
     */
    @Test
    @DisplayName("create() — id is a non-blank, valid UUID")
    fun testUuidIsGenerated() {
        val ds = BoltDataSource.create("UUID Test", "bolt://localhost:7687")

        assertNotNull(ds.id, "id must not be null")
        assertTrue(ds.id.isNotBlank(), "id must not be blank")

        // Attempt to parse as a UUID — throws IllegalArgumentException if invalid.
        val parsed: UUID = UUID.fromString(ds.id)
        assertEquals(ds.id, parsed.toString(), "id must round-trip through UUID.fromString/toString")
    }

    /**
     * Verifies that two separate invocations of [BoltDataSource.create] with
     * identical arguments produce instances with **different** IDs, confirming that
     * a fresh UUID is generated on each call.
     */
    @Test
    @DisplayName("create() — two separate calls produce different UUIDs")
    fun testTwoInstancesHaveDifferentIds() {
        val ds1 = BoltDataSource.create("Same Name", "bolt://localhost:7687")
        val ds2 = BoltDataSource.create("Same Name", "bolt://localhost:7687")

        assertNotEquals(ds1.id, ds2.id, "Each factory call must generate a unique UUID")
    }

    // =========================================================================
    // Colour tests
    // =========================================================================

    /**
     * Verifies that the default [BoltDataSource.color] value is non-blank and
     * starts with `#` (i.e. is a CSS hex colour string).
     */
    @Test
    @DisplayName("color — default colour is a non-blank CSS hex string")
    fun testColorDefault() {
        val ds = BoltDataSource.create("Color Test", "bolt://localhost:7687")

        assertTrue(ds.color.isNotBlank(), "default color must not be blank")
        assertTrue(ds.color.startsWith("#"), "default color must be a CSS hex string starting with #")
    }

    // =========================================================================
    // Data class copy tests
    // =========================================================================

    /**
     * Verifies that Kotlin's `data class` `copy()` function preserves the original
     * [BoltDataSource.id] when no `id` argument is supplied, and correctly overrides
     * the specified field.
     */
    @Test
    @DisplayName("copy() — preserves id and overrides specified field")
    fun testCopy() {
        val original = BoltDataSource.create("Original", "bolt://localhost:7687")
        val copied = original.copy(name = "Renamed")

        assertEquals(original.id, copied.id, "copy() must preserve the original id")
        assertEquals("Renamed", copied.name, "copy() must override the name field")
        assertEquals(original.url, copied.url, "copy() must preserve unspecified fields")
        assertEquals(original.username, copied.username)
        assertEquals(original.database, copied.database)
        assertEquals(original.sslEnabled, copied.sslEnabled)
        assertEquals(original.connectionTimeoutSeconds, copied.connectionTimeoutSeconds)
        assertEquals(original.color, copied.color)
    }

    // =========================================================================
    // URL scheme validation (documentary tests)
    // =========================================================================

    /**
     * Documents that a valid Bolt data source URL starts with `bolt://`.
     *
     * This test does not invoke plugin code — it validates the URL convention
     * expected by [com.graphdbplugin.dialog.AddEditDataSourceDialog]'s validation
     * logic and the Neo4j Java Driver.
     */
    @Test
    @DisplayName("URL validation — bolt:// scheme is accepted")
    fun testUrlValidation_bolt() {
        val url = "bolt://localhost:7687"
        assertTrue(
            url.startsWith("bolt://") || url.startsWith("neo4j://"),
            "A valid URL must start with bolt:// or neo4j://"
        )
    }

    /**
     * Documents that a valid Neo4j data source URL starts with `neo4j://`.
     *
     * This test validates the URL convention expected by
     * [com.graphdbplugin.dialog.AddEditDataSourceDialog] and the Neo4j Java Driver.
     */
    @Test
    @DisplayName("URL validation — neo4j:// scheme is accepted")
    fun testUrlValidation_neo4j() {
        val url = "neo4j://localhost:7687"
        assertTrue(
            url.startsWith("bolt://") || url.startsWith("neo4j://"),
            "A valid URL must start with bolt:// or neo4j://"
        )
    }

    // =========================================================================
    // Color palette tests
    // =========================================================================

    /**
     * Verifies that the [BoltDataSource.COLOR_PALETTE] constant contains exactly
     * 8 entries (matching the 8 swatches shown in the dialog's colour picker).
     */
    @Test
    @DisplayName("COLOR_PALETTE — contains exactly 8 colour entries")
    fun testColorPaletteSize() {
        assertEquals(8, BoltDataSource.COLOR_PALETTE.size, "COLOR_PALETTE must contain exactly 8 colours")
    }

    /**
     * Verifies that every entry in [BoltDataSource.COLOR_PALETTE] is a valid CSS
     * hex colour string (non-blank, starts with `#`, length of 7).
     */
    @Test
    @DisplayName("COLOR_PALETTE — all entries are valid CSS hex colours")
    fun testColorPaletteFormat() {
        for (color in BoltDataSource.COLOR_PALETTE) {
            assertTrue(color.isNotBlank(), "Palette colour must not be blank")
            assertTrue(color.startsWith("#"), "Palette colour must start with #: $color")
            assertEquals(7, color.length, "Palette colour must be 7 characters (#RRGGBB): $color")
        }
    }
}
